/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:2c4639b1-6335-498a-8ead-0ef4c6c87435",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_BhCnBXqrD",
    "aws_user_pools_web_client_id": "2b66c5vmkkn7ah4qmsqb7g1s5",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://njnkpp4mqjaclf4pi2ffgfrufy.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
